version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgressql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_EMAIL_PG}
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASS_PG}
    ports:
      - 5050:${DB_PASS_PG}
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT=${DB_PORT}
    ports:
      - 3306:${DB_PORT}
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=mysql
    ports:
      - 8080:80